.policies[$id] as $p |
([.policies | keys[] | select(. != $id) | "mail-agent-" + . + "@%i.service"] | join(" ")) as $others |
["[Unit]",
 "Description=Isolated mail-agent " + $id + " stream %i",
 "BindsTo=mail-agent-firewall.service",
 "After=mail-agent-firewall.service",
 (if $others != "" then "Conflicts=" + $others, "After=" + $others else empty end),
 "[Service]", "Type=exec", "DynamicUser=yes",
 "SupplementaryGroups=mail_agent_submit mail_agent_results " + ($p.groups | join(" ")),
 "StateDirectory=mail-agent-%i", "StateDirectoryMode=0700",
 "RuntimeDirectory=mail-agent-%i", "RuntimeDirectoryMode=0700",
 "WorkingDirectory=/var/lib/mail-agent-%i", "UMask=0007",
 "Slice=mailagent-" + ($p.network // $id) + ".slice",
 "EnvironmentFile=/etc/mail-agent/policies/" + $id + ".env",
 "Environment=MAIL_AGENT_SYSTEM_POLICY=" + $id,
 "ExecStartPre=+/usr/local/libexec/mail-agent/mail-agent-system-verify " + $id + " %i",
 "ExecStart=/usr/local/libexec/mail-agent/mail-agent-system-envelope " + $id + " %i run",
 "ExecStopPost=+/usr/local/libexec/mail-agent/mail-agent-system-verify " + $id + " %i",
 "ExecStopPost=/usr/local/libexec/mail-agent/mail-agent-system-envelope " + $id + " %i export",
 "Restart=no", "KillMode=control-group", "TimeoutStopSec=30s",
 "NoNewPrivileges=yes", "CapabilityBoundingSet=", "AmbientCapabilities=",
 "PrivateDevices=yes", "DevicePolicy=closed", "ProtectSystem=strict",
 "ProtectHome=read-only", "ProtectControlGroups=yes", "Delegate=no",
 "RestrictNamespaces=yes", "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6",
 "ReadWritePaths=-/var/lib/mail-agent-results/%i " + $p.shared + " " + $p.runtime.cache + " " + $p.runtime.auth,
 "CPUQuota=150%", "TasksMax=512", "MemoryMax=8G", "RuntimeMaxSec=2h",
 "StandardOutput=journal", "StandardError=journal", ""] | join("\n")
