#!/bin/sh
set -eu

printf "%s\n" "$@" > "$CASE_ROOT/launcher-arguments"
printf "%s\n" "${MAIL_AGENT_RESEARCH_TMP:-}" > "$CASE_ROOT/research-directory"

while [ "$#" -gt 0 ]; do
    case $1 in
        -c|-r|-w) shift 2 ;;
        *) break ;;
    esac
done

exec "$@"
